### ISSUE TITLE
SSL is not working

### ISSUE THREAD

**Issue by ghost** [samiavasil/QtWebApp#2]
Hi,

nice work. But I can't get it to work with ssl.
LOG:
HttpListener: New connection
HttpConnectionHandler (0x55d339802740): SSL is enabled
HttpConnectionHandler (0x55d339802740): constructed
DBG: All Connection handlers:  2   Busy:  2   Free:  0
HttpConnectionHandler (0x55d339802740): thread started
HttpConnectionHandler (0x55d339802740): handle new connection
HttpConnectionHandler (0x55d339802740): SSL is enabled
HttpConnectionHandler (0x55d339802740): Starting encryption
qt.network.ssl: QSslSocket: cannot call unresolved function SSLv23_server_method
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_CTX_new
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_library_init
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error
qt.network.ssl: QSslSocket: cannot call unresolved function ERR_get_error

I build the app with Qt5.10. Everything works fine without ssl.

**Comment by samiavasil** [comment]
Hello ,
I'm not sure is this is a issue in your side but I found some similar outputs in google for example :

https://stackoverflow.com/questions/10846536/unresolved-functions-while-working-with-qsslsocket
https://stackoverflow.com/questions/41857883/qsslsocket-cannot-call-unresolved-function
https://github.com/wkhtmltopdf/wkhtmltopdf/issues/3001

I thing where this issue is related to libsssl, please can You check are some of the links can help you to resolve the issue..

**Comment by ghost** [comment]
Installing libssl1.0-dev on Debian Testing solved the problem.

Thanks

**Comment by samiavasil** [comment]
Thanks for information
